### PR TITLE
Async package

### LINKED ISSUE #10: Change to `AsyncPackage`
I can't publish a new release for VS 2019 until we switch to AsyncPackage instead of Package.

A first attempt shows that there are a lot of assumptions about synchronous initialization throughout the code. It'll be big and intrusive.

That said, VS 2019 still seems to work okay, so if you want it you can use the attached VSIX. This is just a Marketplace limitation.

[IndentGuide v16.vsix.zip](https://github.com/zooba/indentguide/files/3183429/IndentGuide.v16.vsix.zip)

### LINKED ISSUE #13: No VS2019 version in the gallery
The README says
> The latest release in the gallery supports Visual Studio 2019 and Visual Studio 2017.

but there is no 2019 version. Have you submitted it yet?

### PR DESCRIPTION
**Pull request by Thieum**
fixes #10 
fixes #13 

tested in VS2017 / VS2019

inspired by what has been done in https://github.com/iccfish/indent-guides-mod

### CODE REVIEW

**Comment by Thieum** [comment]
@zooba Let me know if there is anything that can be improved.

**Comment by Thieum** [comment]
ping @zooba

**Comment by zooba** [comment]
Is it really this simple? I thought I got this far in my own attempt and starting hitting race conditions.

Can you make sure that it works when you quit VS with an editor open, then double-click the solution file to get it back? Startup is what I'm most worried about.

**Comment by Thieum** [comment]
@zooba I tried the use case you've described with VS2019 only, VS2017 only and alternating between the two without any issue. I have VS2019 - 16.2.4 and VS2017 - 15.9.15 .

Alternatively I tried the hard way you were describing and hit a wall I describe here: https://github.com/zooba/indentguide/issues/10#issuecomment-493510206 (I got the same kind of issue in another extension I tried to migrate - https://github.com/Thieum/InheritDoc/tree/vs2019-support - There is something I'm missing in the transition between the two versions of the API, but I cannot figure out what so far :/ )

**Comment by zooba** [comment]
I'm going to merge this as-is, and then hopefully will get some time to test it myself next week. If it's all good, I'll put out a release.

**Pull request merged**
